### ISSUE TITLE
Cannot generate table named "order"

### ISSUE THREAD

**Issue by saggafarsyad** [adrianandrei-ca/staruml-postgresql#10]
Hello,

I have an issue while generating SQL if it has table named `order`, whether the entity name is `order` or entity with **table** tag is set to `order`. It said:

`Table name is not valid: order. Please edit table tag for <entity_name>`

The generated SQL for order table will be

```sql
CREATE TABLE public. (
  id varchar(36) NOT NULL
  ...
  ...
)
```

**Comment by adrianandrei-ca** [comment]
Please do not use order as a table name. It is a reserved keyword. You can change it to CUSTOMER_ORDER for instance. Adrian-------- Original Message --------Subject: [adrianandrei-ca/staruml-postgresql] Cannot generate table named "order" (#10)From: Saggaf Arsyad To: adrianandrei-ca/staruml-postgresql CC: Subscribed Hello,
I have an issue while generating SQL if it has table named order, whether the entity name is order or entity with table* tag is set to order. It said:
Table name is not valid: order. Please edit table tag for <entity_name>
The generated SQL for order table will be
CREATE TABLE public. (
  id varchar(36) NOT NULL
  ...
  ...
)

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/adrianandrei-ca/staruml-postgresql","title":"adrianandrei-ca/staruml-postgresql","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/adrianandrei-ca/staruml-postgresql"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Cannot generate table named \"order\" (#10)"}],"action":{"name":"View Issue","url":"https://github.com/adrianandrei-ca/staruml-postgresql/issues/10"}}}
