### ISSUE TITLE
Support for StarUML 3

### ISSUE THREAD

**Issue by ShakeNBake** [adrianandrei-ca/staruml-postgresql#13]
Hi @adrianandrei-ca !
Do you have any plans to add support for StarUML 3? It doesn't seem to work in v.3, nor is it registered as an extension for V3 here: http://staruml.io/extensions

**Comment by adrianandrei-ca** [comment]
Need to find the time. Adrian-------- Original Message --------Subject: [adrianandrei-ca/staruml-postgresql] Support for StarUML 3 (#13)From: ShakeNBake To: adrianandrei-ca/staruml-postgresql CC: adrianandrei-ca ,Mention Hi @adrianandrei-ca !
Do you have any plans to add support for StarUML 3? It doesn't seem to work in v.3, nor is it registered as an extension for V3 here: http://staruml.io/extensions

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/adrianandrei-ca/staruml-postgresql","title":"adrianandrei-ca/staruml-postgresql","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/adrianandrei-ca/staruml-postgresql"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Support for StarUML 3 (#13)"}],"action":{"name":"View Issue","url":"https://github.com/adrianandrei-ca/staruml-postgresql/issues/13"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/adrianandrei-ca/staruml-postgresql/issues/13",
"url": "https://github.com/adrianandrei-ca/staruml-postgresql/issues/13",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Support for StarUML 3 (#13)",
"sections": [
{
"text": "",
"activityTitle": "**ShakeNBake**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@ShakeNBake",
"facts": [
{
"name": "Repository: ",
"value": "adrianandrei-ca/staruml-postgresql"
},
{
"name": "Issue #: ",
"value": 13
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"adrianandrei-ca/staruml-postgresql\",\n\"issueId\": 13,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"adrianandrei-ca/staruml-postgresql\",\n\"issueId\": 13\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/adrianandrei-ca/staruml-postgresql/issues/13"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 350429924\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by adrianandrei-ca** [comment]
Okay, looks simple enough. I started it. Adrian-------- Original Message --------Subject: [adrianandrei-ca/staruml-postgresql] Support for StarUML 3 (#13)From: ShakeNBake To: adrianandrei-ca/staruml-postgresql CC: adrianandrei-ca ,Mention Hi @adrianandrei-ca !
Do you have any plans to add support for StarUML 3? It doesn't seem to work in v.3, nor is it registered as an extension for V3 here: http://staruml.io/extensions

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/adrianandrei-ca/staruml-postgresql","title":"adrianandrei-ca/staruml-postgresql","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/adrianandrei-ca/staruml-postgresql"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Support for StarUML 3 (#13)"}],"action":{"name":"View Issue","url":"https://github.com/adrianandrei-ca/staruml-postgresql/issues/13"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/adrianandrei-ca/staruml-postgresql/issues/13",
"url": "https://github.com/adrianandrei-ca/staruml-postgresql/issues/13",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Support for StarUML 3 (#13)",
"sections": [
{
"text": "",
"activityTitle": "**ShakeNBake**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@ShakeNBake",
"facts": [
{
"name": "Repository: ",
"value": "adrianandrei-ca/staruml-postgresql"
},
{
"name": "Issue #: ",
"value": 13
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"adrianandrei-ca/staruml-postgresql\",\n\"issueId\": 13,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"adrianandrei-ca/staruml-postgresql\",\n\"issueId\": 13\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/adrianandrei-ca/staruml-postgresql/issues/13"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 350429924\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by drognisep** [comment]
Any update on this?
